/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package by.cnb.liferay.portlet.collapsableadvert.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Advert service. Represents a row in the &quot;Advert&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link by.cnb.liferay.portlet.collapsableadvert.model.impl.AdvertModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link by.cnb.liferay.portlet.collapsableadvert.model.impl.AdvertImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Advert
 * @see by.cnb.liferay.portlet.collapsableadvert.model.impl.AdvertImpl
 * @see by.cnb.liferay.portlet.collapsableadvert.model.impl.AdvertModelImpl
 * @generated
 */
public interface AdvertModel extends BaseModel<Advert> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a advert model instance should use the {@link Advert} interface instead.
	 */

	/**
	 * Returns the primary key of this advert.
	 *
	 * @return the primary key of this advert
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this advert.
	 *
	 * @param primaryKey the primary key of this advert
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this advert.
	 *
	 * @return the uuid of this advert
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this advert.
	 *
	 * @param uuid the uuid of this advert
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the entry ID of this advert.
	 *
	 * @return the entry ID of this advert
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this advert.
	 *
	 * @param entryId the entry ID of this advert
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the group ID of this advert.
	 *
	 * @return the group ID of this advert
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this advert.
	 *
	 * @param groupId the group ID of this advert
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this advert.
	 *
	 * @return the company ID of this advert
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this advert.
	 *
	 * @param companyId the company ID of this advert
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this advert.
	 *
	 * @return the create date of this advert
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this advert.
	 *
	 * @param createDate the create date of this advert
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this advert.
	 *
	 * @return the modified date of this advert
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this advert.
	 *
	 * @param modifiedDate the modified date of this advert
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this advert.
	 *
	 * @return the name of this advert
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this advert.
	 *
	 * @param name the name of this advert
	 */
	public void setName(String name);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Advert advert);

	public int hashCode();

	public CacheModel<Advert> toCacheModel();

	public Advert toEscapedModel();

	public String toString();

	public String toXmlString();
}